import Alpine from 'alpinejs';
import billView from './components/bill-view';
import clock from './components/clock';
import confirmDialog from './components/confirm-dialog';
import dailyBalance from './components/daily-balance';
import documentView from './components/document-view';
import grnForm from './components/grn-form';
import grnView from './components/grn-view';
import jobForm from './components/job-form';
import jobView from './components/job-view';
import productForm from './components/product-form';
import posCart from './components/pos-cart';
import productStock from './components/product-stock';
import quotationForm from './components/quotation-form';
import quotationView from './components/quotation-view';
import recordForm from './components/record-form';
import salaryIssue from './components/salary-issue';
import salaryView from './components/salary-view';
import searchableSelect from './components/searchable-select';
import serviceForm from './components/service-form';
import shiftView from './components/shift-view';
import stockItemsForm from './components/stock-items-form';
import supplierView from './components/supplier-view';
import teamManager from './components/team-manager';
import warrantyClaim from './components/warranty-claim';

window.Alpine = Alpine;

Alpine.data('billView', billView);
Alpine.data('clock', clock);
Alpine.data('confirmDialog', confirmDialog);
Alpine.data('dailyBalance', dailyBalance);
Alpine.data('documentView', documentView);
Alpine.data('grnForm', grnForm);
Alpine.data('grnView', grnView);
Alpine.data('jobForm', jobForm);
Alpine.data('jobView', jobView);
Alpine.data('productForm', productForm);
Alpine.data('posCart', posCart);
Alpine.data('productStock', productStock);
Alpine.data('quotationForm', quotationForm);
Alpine.data('quotationView', quotationView);
Alpine.data('recordForm', recordForm);
Alpine.data('salaryIssue', salaryIssue);
Alpine.data('salaryView', salaryView);
Alpine.data('searchableSelect', searchableSelect);
Alpine.data('serviceForm', serviceForm);
Alpine.data('shiftView', shiftView);
Alpine.data('stockItemsForm', stockItemsForm);
Alpine.data('supplierView', supplierView);
Alpine.data('teamManager', teamManager);
Alpine.data('warrantyClaim', warrantyClaim);

Alpine.start();
